### PR TITLE
Updated to null-safety, removed Firebase from Android

### PR DESCRIPTION
**Pull request by aaqibism**
I know you have been working hard on the update, so I wanted to help where I could. I migrated the main plugin, not the example, to null-safety and I removed the FCM service for Android. I've tested this plugin along side the firebase_messaging plugin and it works flawlessly. You can set up firebase_messaging's background handler to run the following function and it will create a notification from this plugin every time you receive a push notification, even if the app has been killed. This allows use of action buttons with the flexibility of push notifications. The only thing I've been trying to figure out is how to not show the default FCM notification and only show the AwesomeNotification instead.

```
Future<dynamic> _onFCM(RemoteMessage message) async {
  WidgetsFlutterBinding.ensureInitialized();
  AwesomeNotifications().createNotification(
    content: NotificationContent(
      channelKey: "Basic",
      id: 4,
      title: message.notification?.title ?? "New Notification",
      body: message.notification?.body ?? "",
    ),
    actionButtons: [
      NotificationActionButton(
        key: 'Reply',
        label: 'Reply',
        buttonType: ActionButtonType.InputField,
      ),
    ],
  );
}
```

#97 
#128

### CODE REVIEW

**Comment by rafaelsetragni** [comment]
Excelent! Now i gonna check your changes and merge it with the actual 0.0.6. Thank you so much!!

**Comment by aaqibism** [comment]
@rafaelsetragni  One thing I noticed while going through your source code is that you seem to use nullable values very often, but you could very well make many of them non-nullable. For example, in the Android Java code you have a HashMap for default values in case the user enters a null value. While that's a great idea, I think it would just be easier to make some of those values non-nullable in the first place (Notification id, title, channel key, etc). It would make your project more maintainable for yourself as well because you don't have to handle so many different edge cases. Just my 2 cents.

**Comment by rafaelsetragni** [comment]
> @rafaelsetragni One thing I noticed while going through your source code is that you seem to use nullable values very often, but you could very well make many of them non-nullable

They are nullable many times because when you receive a push data, you are not sure that any field will be filled, even the non-nullable. So, I made a hash map with these default values ​​to ensure that at least the critical fields will be filled, even in the worst scenario, and the notification will be delivered.

**Comment by aaqibism** [comment]
I think now that you’re removing firebase notifications service you can be confident that the notification that’s delivered follows the correct format. Even if a scheduled notification is corrupted somehow, it might be better not to show a notification and instead display an error for the developer to handle. That way there’s never any weird behavior to deal with.

**Pull request merged**
