### PR TITLE
Update intl

### PR DESCRIPTION
**Pull request by mbfakourii**
update intl to version ```0.18.0```

### CODE REVIEW

**Review by clintonrocksmith — APPROVED** [review]

**Comment by rafaelsetragni** [comment]
Thanks guys for the update, but this plugin version is already updated to  `intl: ^0.18.1` in version 0.7.5-dev.2+1. But thank you so much anyway!

**Comment by sebastianbuechler** [comment]
> Thanks guys for the update, but this plugin version is already updated to `intl: ^0.18.1` in version 0.7.5-dev.2+1. But thank you so much anyway!

@rafaelsetragni, do you mind still creating a version with `intl`: ^0.18.0? Most of the packages out there are only on the 0.18.0 version (if even) and with your restriction a lot of people won't be able to use `awesome_notifications` in combination with Dart SDK 3 for a long time because of filed dependency resolvement. I know it's nice to have the newest version, but unfortunately after such a big update a lot of other packages are slow to update.

**Comment by rafaelsetragni** [comment]
You can use the dependency_override on pubspec.yaml to set manually any plugin version for all packages

**Comment by sebastianbuechler** [comment]
@rafaelsetragni Thanks for your reply. Even though everybody that needs it could do that indeed, it will take a lot of time for each individual to debug and figure that out. I think it would be helpful in the future to first introduce major versions for such big dependencies (`intl` is everywhere), and then, if necessary, pin to the latest one directly. It does not really hurt but helps a lot.

**Pull request closed without merging**
