### PR TITLE
feat: template updated and refactored for latest flutter version

### PR DESCRIPTION
**Pull request by OutdatedGuy**
## Changes

1. Re-wrote plugin files with below command:
   ```bash
   flutter create --overwrite --org="me.carda" --project-name="awesome_notifications" -t plugin --platforms="android,ios" -i objc -a java --description="A complete solution to create Local and Push Notifications, customizing buttons, images, sounds, emoticons and applying many different layouts for Flutter apps." .
   ```

1. Removed plugin and example code/directories for `linux`, `macos`, `web` and `windows` as their template was redundant and pretty much outdated.
1. Updated all non-plugin files (the ones not written by package author like `.java`, `.swift`, `.m` etc.)
1. Did not change any actual plugin source code files
1. Deleted all unnecessary files that are not meant to be included in version control.
1. Deleted all directories and files that are mentioned in the `.gitignore` file but are still version controlled.

## Styling and Formatting

1. Added temporary linter rule `required_trailing_commas`.
1. Formatted all dart code with the following commands:
   ```bash
   dart fix --apply;
   dart format .;
   cd example;
   dart fix --apply;
   dart format .;
   ```
1. This fixed all `dart` warnings and formatted code in a clean and readable way
1. Removed the temporary linter rule `required_trailing_commas`.
1. Formatted all `java` code with the recommended formatting style
1. Formatted all markdown files with the recommended formatting style

## Testing

1. Ran the flutter test from vs-code and got all passed. (401/401)
1. Ran the example app (`example/lib/main_complete.dart`) on both android and ios devices and all platform compatible notification worked properly

### P.S.

Making the prophecy true:
Screenshot 2023-12-20 at 8 33 41 AM

### CODE REVIEW

**Review by OutdatedGuy — COMMENTED** [review]
@rafaelsetragni, just went over the PR files and reviewed them. It was a nightmare.

It'll be a headache for you too, so just a friendly note that you can just skip checking any `.dart` files cuz each and every dart file that's changed is done using the `dart format .` command so there are no code changes.

It'll save you a lot of time and headache if you skip checking any files from the `lib/`, `test/` and `example/lib/` directories.

**Comment by OutdatedGuy** [comment]
@rafaelsetragni, updated PR to the latest commit in _master_ branch.

Ran example app on **Android** and **iOS** emulator successfully and tested that all notifications are displayed properly.

Ran testing tool and all **401** tests passed

**Comment by rafaelsetragni** [comment]
And why not about implementing the missing libraries? They are in the next development milestones

**Comment by OutdatedGuy** [comment]
Hi @rafaelsetragni, I don't understand what you mean by missing libraries.

In this PR, I just updated the plugin code to the latest flutter standards. So they are fully up-to-date with the master branch and latest flutter version.

**Comment by rafaelsetragni** [comment]
I mean, the missing platform implementations. They are in the development milestones.

**Comment by OutdatedGuy** [comment]
@rafaelsetragni do you mean linux, macos, web and windows? They are not yet implemented so having boilerplate code for them is unnecessary and adds complexity.

Also when deciding to implement, they can be easily added using the below command:

```bash
flutter create --platforms="android,ios,<any-other-platform>" --overwrite --org="me.carda" --project-name=awesome_notifications -t plugin -i objc -a java --description="A complete solution to create Local and Push Notifications, customizing buttons, images, sounds, emoticons and applying many different layouts for Flutter apps." .
```

After running the above command, we can discard the overwritten code for already implemented platform and can add missing implementation for the newly added platform.

**Comment by OutdatedGuy** [comment]
@rafaelsetragni ohh I see, so if the platforms are currently under development, then yes that would be problematic.

I will run the command mentioned in [this comment](https://github.com/rafaelsetragni/awesome_notifications/pull/906#issuecomment-1884856302) to update template for those platform so it wouldn't break the development work.

Can you tell me which platforms to add again?

**Comment by rafaelsetragni** [comment]
But there are another problems:

1. These commands are changing a lot of files at once and unfortunately I don't have time to evaluate each change (it turns out there is a lot of code reformatting), and this evaluation is mandatory for the entire PR.
2. All Dart plug-ins are evaluated and scored on pub.dev for some aspects, including code formatting. If the code was changed by the commands above, it is possible that pub.dev considers the new version as non-standard, which will harm the score and consequently the plugin's ranking in the searches.

If you want to help us, you can implement just one of the incomplete platforms with just basic notification functionality, following the same structures used for Android and iOS. This is a change that will help us a lot.

**Comment by OutdatedGuy** [comment]
> 2\. All Dart plug-ins are evaluated and scored on pub.dev for some aspects, including code formatting. If the code was changed by the commands above, it is possible that pub.dev considers the new version as non-standard, which will harm the score and consequently the plugin's ranking in the searches.

The formatting was done using `pub.dev` dart standards mentioned [here](https://pub.dev/help/scoring#pass-static-analysis). So it wouldn't cause any problems.


> If you want to help us, you can implement just one of the incomplete platforms with just basic notification functionality, following the same structures used for Android and iOS. This is a change that will help us a lot.

I don't have adequate knowledge of any native platform to implement even basic notification for them.

> 1\. These commands are changing a lot of files at once and unfortunately I don't have time to evaluate each change (it turns out there is a lot of code reformatting), and this evaluation is mandatory for the entire PR.

I understand your concern. Here as a package publisher myself, I would suggest to publish the changes in this PR as a `pre-lease` / `beta` update.

So it won't affect the package score and reach to developers and simultaneously others can test it out and can notify  about an issue, if any.

**Pull request closed without merging**
