### PR TITLE
Fix (Custom Sound or Icon not Showing in Release)

### PR DESCRIPTION
**Pull request by madd-project**
People are coming up with the Issue of not seeing the custom icons or the custom sounds in the Action (i.e in the APK or release). So I Decided to Search up the whole web, For this, and Found that, Adding just Two lines of code in the AndroidManifest.xml we can remove the error of not seeing the Custom Sounds and Icons in the Action.

### CODE REVIEW

**Comment by rafaelsetragni** [comment]
ive couldnt find any documentation that relates the issues with files reference in apk release with the changes sent by you. So, until i get a information confirm that this steps fix the issue, i can merge it.

**Comment by madd-project** [comment]
@rafaelsetragni This is all yours, 😁.
If somehow it will not work, I will never leave contribution to this package. 

And Most probably, It will Work.. 💪

**Comment by mapacheverdugo** [comment]
I don't know if the issue that you are referring to is the same that what happens to me, but you can see my case with the following screenshots:

In debug
Notification in debug

In APK release
photo_2021-07-15 21 45 23

Sadly, In my project I already have those lines of code that you are trying to add, and as you can see the issue persist

**Comment by bbence84** [comment]
@mapacheverdugo 

I also had the same issue, and finally managed to fix it by adding a keep.xml. I had the icon in a drawable resource folder and also the issue that the icon was blank in release mode. How to fix it:
1. Create a folder called "raw" under android/app/src/main/res
2. Create a keep.xml file and add the following content:

<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/slow_spring_board" />

Save it and rebuild.

Not sure if the AndroidManifest.XML change was also neccessary, I kept it there, but without the keep.xml, I still had the issue even after the AndroidManifest.XML change.

**Comment by rafaelsetragni** [comment]
>     2\. Create a keep.xml file and add the following content

Try to use the prefix `res_` before the file name (sound and image) and see if its fixed.
But i enjoyed a lot this keep.xml solution! Its a good idea to put this tip into the README file.

Sources:
[https://stackoverflow.com/questions/5848761/how-can-i-force-proguard-to-keep-my-xml-resource-file](https://stackoverflow.com/questions/5848761/how-can-i-force-proguard-to-keep-my-xml-resource-file)
[https://developer.android.com/studio/build/shrink-code#configuration-files](https://developer.android.com/studio/build/shrink-code#configuration-files)

**Review by rafaelsetragni — CHANGES_REQUESTED** [review]
@madd-project  can you undo the old tip, update the README file and post this `keep.xml` tip on our common known issues?

That way i can finally merge your branch.

**Pull request merged**
