### PR TITLE
Background click

### PR DESCRIPTION
**Pull request by saharvx9**
Support for android background + terminated click action
Supoort for ios :
configure group buttons,when app is terminated and background the os will not display if you did not configure it.
Support click in background
Click when app terminated - bug,first time click nothing happend second time working
**Big Notice:**
When working with firebase + awesome notifications it will not work together because this library implement `UserNotificationCenter` delegate too(same as firebase).
This is why all the push in the background not working + foreground.
So i  fix it too when add another stream `otherNotificationTypeSubject` for receiving all!

### CODE REVIEW

**Comment by rafaelsetragni** [comment]
I couldn't find any testing method in the example application. How did you test the features?

**Comment by rafaelsetragni** [comment]
I did a video to explain the problems that i found.
Is not a well done video, but i believe is necessary to communicate to you the issues that i found with this branch.

[Awesome Notifications 0.7.0 - Current progress with background notification actions](https://www.youtube.com/watch?v=HMq2wCe5ujE)

**Comment by gbbest15** [comment]
please i am waiting for this.... i am building a social media app that is looking up to this features... just like whatsApp that you reply chat in background and when terminated... please i no that i am not the only one waiting.... please be fast. i am begging.

**Comment by rafaelsetragni** [comment]
I'm trying to be as fast as possible, but i need to be sure about how everything should works with the isolates.
Keep calm and stay strong!

**Comment by rafaelsetragni** [comment]
I figured out how to properly close FlutterEngine. You need to destroy all elements in the main class plugin and not use static objects.

I also figured out how to run dart code in the background thread, so I was able to create the `SilentAction` and `SilentBackgroundAction` types. (Yes, I changed the names of the types to make them easier to understand)

Version 0.0.7 for Android is ready to go!!!
Check it out for me as I finish the iOS code.

**Comment by gbbest15** [comment]
Okay... thanks so much. I will start coding. Please alert us if the iOS is ready... thanks so much.

**Comment by rafaelsetragni** [comment]
My virtual mac is being so slow that took me 30 min to startup xcode and i give up to wait it processing all files. Im being uncapable to type a single line of code.

I gonna try to code on windows using Visual Studio Code, but this is like programming with eyes closed.

**Comment by gbbest15** [comment]
> My virtual mac is being so slow that took me 30 min to startup xcode and i give up to wait it process all files. Im being uncapable to type a single line of code.
> 
> I gonna try to code on windows using Visual Studio Code, but this is like programming with eyes closed.

If there is any way to help, I can do that, i am using macbook...

**Comment by saharvx9** [comment]
> I figured out how to properly close FlutterEngine. You need to destroy all elements in the main class plugin and not use static objects.
> 
> I also figured out how to run dart code in the background thread, so I was able to create the `SilentAction` and `SilentBackgroundAction` types. (Yes, I changed the names of the types to make them easier to understand)
> 
> Version 0.0.7 for Android is ready to go!!!
> Check it out for me while I finish the iOS code.

Ok thinx, are you need that i will fix it?
In adittion what you need i will do in ios?
Notice for ios background click evenrs must be configure first.
Moreover in ios your are override the main userNotifictiinDeletegate , so if i am using firebase or another library it will not work so i did that all pushes will be observe,even if the pattern of the push is not same as u, if you have other idea how to fix it i will glad to hear about it :)

**Review by rafaelsetragni — CHANGES_REQUESTED** [review]

**Comment by rafaelsetragni** [comment]
> 
> 
> > I figured out how to properly close FlutterEngine. You need to destroy all elements in the main class plugin and not use static objects.
> > I also figured out how to run dart code in the background thread, so I was able to create the `SilentAction` and `SilentBackgroundAction` types. (Yes, I changed the names of the types to make them easier to understand)
> > Version 0.0.7 for Android is ready to go!!!
> > Check it out for me while I finish the iOS code.
> 
> Ok thinx, are you need that i will fix it?
> In adittion what you need i will do in ios?
> Notice for ios background click events are must be configure first.
> Moreover in ios your are override the main userNotifictiinDeletegate , so if i am using firebase or another library it will not work so i did that all pushes will be observe,even if the pattern of the push is not same as u, if you have other idea how to fix it i will glad to hear about it :)

I need to replicate how the plugin works on Android to iOS, trying to always use the same class names and the same enumerators. This makes it easier to understand and maintain and evolve across platforms in the future. You can notice from the source that I always try to follow this pattern of using the closest possible architecture between platforms. I believe the source code is the best software documentation possible.

An important note about NotificationActionTypes on NotificationContentModel for iOS. It will not work because "Apple". First i thought to deactivate the feature for Android and leveling everything down. But i figured out later that i can only leave an observation on README and leave this feature only working on Android without any problem.

**Comment by saharvx9** [comment]
i try to understand why in ios you deleted the most necessary classes to display buttons when app is killed
when you are not config ios buttons before you get push with actions it will never display here is documentation about it:
https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types
it will never works for you if you get push from server and not from schedule.

**Comment by rafaelsetragni** [comment]
I asked you the meanings of these classes and you didn't said anything.

**Comment by gbbest15** [comment]
Can you give link to your branch we should check out... I actually stock in this comment

**Comment by saharvx9** [comment]
https://github.com/saharvx9/awesome_notifications/tree/background_click

:)

**Comment by gbbest15** [comment]
Good @rafaelsetragni also can check it out..

**Comment by rafaelsetragni** [comment]
> Sorry for the delay but you deleted very important files i checked it multiple time must configure this actions before you can get push i can send to u video with your merge and my branch before all the changes you made and it not works.(mine work great)

I agree if in case the push clear all categories in iOS. But anyway, we still need to follow the standard way to create buttons, otherwise it will work in some way on local and schedules and another way in push notifications. Everything should work as the same for the final developer, being transparent. Thats why ive asked you about the concept of positive and negative buttons (because we can even use 3 buttons on local, so should the third be called as neutral?)

> In addition i added another stream otherPushStream That can recive all notifction and in your branch you accept only your template of push but in case i need it as data push only u ignore it.
> 
> Moreover u implement usernotfiction delegete in ios so u are blocking the notifictions from another libraries such as firebase so this is the reason i added that stream.
> 

I gonna move everything related to push notifications to the companion plugin. Otherwise we ended up using workarounds to make everything works, and thats is a clear symptom from Apple to not use obsever pattern to distribute the global usernotfiction delegete object. This violates the encapsulation OOP principle to not expose internal sensible variables to another objects and procedures.

> All this mentions i talked about is when the app killed i added a lot of comments in my brach that explain why i added this new models/functions etc...
> 
> For my opinion u should reopen this pr

Ive excluded most of the things that was in your branch because ive realised that these implementations was very focused on your solution and i need to do an wide openned solution for everyone. But is not necessary to reopen the pr. Im still using your btanch to merge and build the iOS package.

Right now i'm working in separate the core awesome notification's methods and classes into a third external package, to let they be reusable between the local plugin and the companion plugin, without create a loop reference in the build process. Thats why ive stopped a litte bit to work on iOS merging for now.

**Comment by gbbest15** [comment]
@rafaelsetragni @saharvx9 i am finding it difficult to implement this with fcm push notification. i am lost.
here is my problem.

```
FirebaseMessaging.onMessage.listen

FirebaseMessaging.onMessageOpenedApp.listen

FirebaseMessaging.instance
.getInitialMessage()
.then((RemoteMessage message) {
});
```
so what will use to replace the call in awesome notification. 

second:
if declear actionBution to 
 NotificationActionButton(
                  key: "REPLY",
                  label: "Reply",
                  buttonType: ActionButtonType.InputField,
                )

how can i call a function from this button.

**Comment by duyjack** [comment]
> When app is in background, if u using my fork u just need to implement one function :)
> 
> ```
> AwesomeNotifications().initialize(
>       // set the icon to null if you want to use the default app icon
>         null,
>         [
>           //Each NotificationChannel is group of notification
>           //in case we want to add another group add another [NotificationChannel]
>           NotificationChannel(
>               importance: NotificationImportance.High,
>               channelKey: NotificationChannel.CHANNEL_KEY,
>               channelName: NotificationChannel.CHANNEL_NAME,
>               channelDescription: NotificationChannel.CHANNEL_DESCRIPTION,
>               defaultColor: Colors.blue,
>               ledColor: Colors.white
>           )
>         ],
>         backgroundClickAction: _observeActionStream
>     );
> ```
> 
> **Notice:** `backgroundClickAction` is for handling clicks when app is killed it must be static/top function for activate goodluck :)
> 
> ```
> static _observeActionStream(ReceivedAction action) async{
>   debugPrint("handle click BACKGROUND: $action");
> }
> ```

Hi @saharvx9 
How to open app when i click on action button?
I use GlobalKey<NavigatorState> and pushNamed but it's not works
I also try runApp(MyApp()) but it's not works

**Pull request merged**
